[FIX] runbot_travis2docker: Fix when the projects on weblate are more 25
Vauxoo/runbot-addons pull request #120
Opened 2017-05-11 22:33 UTC by JesusZapata

2017-05-11 22:36 UTC, JesusZapata commented
@moylop260 
What do you think about this PR?

2017-05-11 22:46 UTC, moylop260 requested changes

2017-05-11 22:46 UTC, moylop260 commented on runbot_travis2docker/models/runbot_branch.py
> +                page+=1
page += 1 
add space between operator
check other lints reñated with this

2017-05-12 12:30 UTC, JesusZapata commented
@moylop260 
I fix the flake8 and pylint related with this PR

2017-05-12 13:15 UTC, merged