[IMP] runbot_gitlab_minimal: Fixes calculated ssh key (#97)
Vauxoo/runbot-addons pull request #98
Opened 2017-03-21 13:15 UTC by JesusZapata

Fixes https://github.com/Vauxoo/runbot-addons/issues/97

2017-03-21 13:28 UTC, JesusZapata commented
@moylop260 
I have tried to put the runbot_gitlab_minimal module to depend on runbot_travis2docker but the method get_ssh_keys of this module is not called

2017-03-21 18:01 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                                       json['committer_email'], repo.base)
What about if 2 users has same email configured?

2017-03-21 18:29 UTC, moylop260 requested changes

2017-03-21 18:29 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +                if (hasattr(build.repo_id, 'uses_gitlab') and
`if getattr(build.repo_id, 'uses_gitlab', False):`

2017-03-21 18:29 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +    def _get_branch_url(self):  # pylint: disable=missing-return
pylint fixes for other PR

2017-03-21 18:29 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +        # pylint: disable=method-compute
pylint fixes for other PR

2017-03-21 18:29 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                return super(RunbotBuild, self).github_status(cr, uid, ids,
pylint fixes for other PR

2017-03-21 18:29 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +            # pylint: disable=missing-return
pylint fixes for other PR

2017-03-21 18:44 UTC, JesusZapata commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                                       json['committer_email'], repo.base)
I have 2 email registered
![image](https://cloud.githubusercontent.com/assets/1387970/24164567/8b309c6c-0e44-11e7-89d5-63525542aa4f.png)
And all good

2017-03-21 18:44 UTC, JesusZapata commented on runbot_travis2docker/models/runbot_build.py
> +                if (hasattr(build.repo_id, 'uses_gitlab') and
@moylop260 
Done

2017-03-21 18:45 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +class RunbotBranclh(models.Model):
typo

2017-03-21 18:47 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +                        keys += rsa['key']
keys += '\n' + rsa['key']

2017-03-21 18:49 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                                       json['committer_email'], repo.base)
You are using 2 emails for 1 user
I'm talking about 2 users with 1 same email configured

I means,
User: JesusZapata
Email: jesus@vauxoo.com

User: JesusZapata2
Email: jesus@vauxoo.com

2017-03-21 19:50 UTC, JesusZapata commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                                       json['committer_email'], repo.base)
![image](https://cloud.githubusercontent.com/assets/1387970/24165621/4198c748-0e47-11e7-9b4e-665b14adb1fe.png)

2017-03-21 20:04 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                        json['author'] = response.json()[0]['username']
Assign `commiter` too

2017-03-21 20:08 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                                       json['committer_email'], repo.base)
We tested and this scenario is not possible
Then is good to continue

2017-03-21 20:12 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                        json['author'] = response.json()[0]['username']
There are cases where the committer is not a user of gitlab
A example is the following commit: https://github.com/Vauxoo/odoo-peru/commit/ae11e24d2d678b327f64637172a88b92eec7526d where the committer `Arturo Flores` don't have github account and we had a TypeError fixed from https://github.com/Vauxoo/runbot-addons/pull/95

Could you review if we will have a special exception for gitlab?

2017-03-21 20:59 UTC, JesusZapata commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                        json['author'] = response.json()[0]['username']
I made more conditions when the gitlab user not found

2017-03-21 21:26 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +                                                   response['user_id'])
Where are you processing the committer and the author here?

2017-03-21 21:50 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +                    stream = requests.get(url, stream=True)
Use github's api to get keys too here, please

2017-03-21 21:50 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +                    ssh_rsa = build.repo_id.github("/users/%s/keys" %
Remove the process of gitlab keys here and use a wrapper from github method

2017-03-21 21:50 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                            data = data[0]
Return a dict-of-dict similar to github

2017-03-21 22:00 UTC, moylop260 commented
Use 2 commits:
1. Changes for gitlab module
2. Changes for t2d module

And migrate the first one to OCA PR, please

2017-03-22 14:06 UTC, JesusZapata commented on runbot_travis2docker/models/runbot_build.py
> +                                                   response['user_id'])
@moylop260 
I changed the way to calculate the github keys

2017-03-22 14:07 UTC, JesusZapata commented
@moylop260 
Change the logic of download the ssh-rsa of github and gitlab

2017-03-22 15:00 UTC, moylop260 requested changes

2017-03-22 15:00 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                    is_url_keys = url.endswith('.keys')
Move `if '/pulls/' in url:` for `get_url` method

2017-03-22 15:00 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +            is_url_keys = False
Delete useless assigned variables

2017-03-22 15:00 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                                    json[own_key] = {'login': data['username']}
`json[own_key] = {'login': len(data) and data[0]['username'] or {}}`

2017-03-22 15:00 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +        if url.endswith('/keys'):
Add a comment of url github vs url gitlab

2017-03-22 15:00 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +        prefix = ('https://%s/api/v3%s'
Add a comment because if using this replace...

`Because gitlab api v3 requires admin to get keys from api but...`

2017-03-22 15:00 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                  if not url.endswith('/keys') else 'https://%s%s')
github vs gitlab url comment

2017-03-22 15:57 UTC, JesusZapata commented
@moylop260 
All changes were made
Thanks for your review

2017-03-22 16:33 UTC, moylop260 approved these changes
Could you use 2 commits 1 by module changed?

2017-03-22 17:38 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
>                  if url:
Is possible a return early using `if not url`?

2017-03-22 17:38 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                    if '/commits/' in url:
use `elif`

2017-03-22 17:38 UTC, moylop260 commented on runbot_gitlab_minimal/models/runbot_repo.py
> +                    if is_url_keys:
use `elif`

2017-03-22 17:40 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +                keys += '\n'.join(rsa['key'] for rsa in ssh_rsa)
Use a `keys += '\n' + '\n'.join...`

2017-03-22 18:24 UTC, JesusZapata commented
@moylop260 
I made all changes what did you request

2017-03-22 18:33 UTC, merged